import React, {Component} from 'react';
import MangaListComponent from './MangaListComponent';
import MangaComponent from './MangaComponent';
import NewMangaComponent from './NewMangaComponent';
import Navbarcomponent from './Navbarcomponent';
import Banner from './Banner';
import DiscoverComponent from './DiscoverComponent';
import{
  BrowserRouter as Router,
  Switch,
  Route
}from "react-router-dom";


class MangaApp extends Component {


  render(){
     return (
       <Router>
         <Banner/>
         <Navbarcomponent />
        <Switch>
          <Route path="/" exact component={MangaListComponent} />
          <Route path="/manga/:id" component={MangaComponent} />
          <Route exact path="/newmanga" component={NewMangaComponent} />
          <Route exact path="/about">
          <div className="container">
          <h1>Made by MoonieBanoonie</h1>
          <p>This is a simple CRUD app where I can keep track of which mangas I read, what chapter I'm currently on and redirecting me to the manga's website to read the manga.
           It's possible to add, update, remove and to filter for a manga based on its title.
           The information is stored on my localhost database. Moreover, under the 'Discover' tab, you will find random manga's, generated by the Jikan API.
           </p>
          <p>Technologies used: Spring Boot, MySQL, React and Jikan API</p>
          </div>
          </Route>
          <Route exact path = "/discover" component={DiscoverComponent}/>
        </Switch>
       </Router>
     )
   }
 }

export default MangaApp
